services:
  nginx:
    init: true
    build: requirements/nginx
    ports:
      - "4443:443"
      - "8080:80"
  wordpress:
    init: true
    build: requirements/wordpress
  mariadb:
    init: true
    build: requirements/mariadb
