services:
  nginx:
    init: true
    build: requirements/nginx
    ports:
      - "4443:443"
    volumes:
      - wordpress:/mnt/app/
    restart: always
  wordpress:
    init: true
    build: requirements/wordpress
    volumes:
      - wordpress:/mnt/app/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
  mariadb:
    init: true
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
  adminer:
    init: true
    build: requirements/adminer
    restart: always
  ftp:
    init: true
    build: requirements/ftp
    restart: always
    volumes:
      - wordpress:/mnt/app/
    ports:
      - "2221:21"
      - "2220:20"
      - "10090-10100:10090-10100"

volumes:
  wordpress:
  db:
