services:
  nginx:
    init: true
    build: requirements/nginx
    ports:
      - "4443:443"
      - "8080:80"
    volumes:
      - wordpress:/mnt/app/
    restart: always
  wordpress:
    init: true
    build: requirements/wordpress
    volumes:
      - wordpress:/mnt/app/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
  mariadb:
    init: true
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

volumes:
  wordpress:
  db:
