services:
  nginx:
    init: true
    build: requirements/nginx
    ports:
      - "4443:443"
      - "8080:80"
    volumes:
      - wordpress:/mnt/app/
  wordpress:
    init: true
    build: requirements/wordpress
    volumes:
      - wordpress:/mnt/app/
  mariadb:
    init: true
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql/

volumes:
  wordpress:
  db:
