services:
  nginx:
    init: true
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/mnt/app/
    restart: always
  wordpress:
    init: true
    build: requirements/wordpress
    volumes:
      - wordpress:/mnt/app/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
  mariadb:
    init: true
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
  adminer:
    init: true
    build: requirements/bonus/adminer
    restart: always
  ftp:
    init: true
    build: requirements/bonus/ftp
    restart: always
    volumes:
      - wordpress:/mnt/app/
    ports:
      - "21:21"
      - "20:20"
      - "10090-10100:10090-10100"
  static-website:
    init: true
    build: requirements/bonus/static-website
    restart: always
  redis:
    init: true
    build:
      context: requirements/bonus/redis/
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
  ssh:
    init: true
    build:
      context: requirements/bonus/ssh/
      args:
        SSH_PASSWORD: ${SSH_PASSWORD}
        SSH_USER: ${SSH_USER}
    restart: always
    volumes:
      - wordpress:/mnt/app/
    ports:
      - "22:22"

volumes:
  wordpress:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wordpress
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/db
